name = "Cobblemon Space Heater+"
author = "Mootoo & Reppamon"
version = "1.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4fc269144d653ecad9f42bbd67587b9201148c8a1b4b64e50919ac6501be2c88"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.244"

[options]
acceptable-game-versions = []
datapack-folder = "tempdata"
