name = "Cobblemon Space Heater+"
author = "Mootoo & Reppamon"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4aee2c33e7b19a73cbe79baea3486916a7973de6fa8555482ca688d6029ce253"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.244"

[options]
acceptable-game-versions = []
datapack-folder = "tempdata"
