name = "Cobblemon Space Heater+"
author = "Mootoo & Reppamon"
version = "1.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b3177ce02dd84794dc5d2fc7a7e07d41a6be22ce59e839ef82ab3f81b42ee0af"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.244"

[options]
acceptable-game-versions = []
datapack-folder = "tempdata"
